package com.kafe.koffee.enums;

public enum NotificationEvent {
	
	   CART_REMINDER,
	   ORDER_PLACED,
	   ORDER_CONFIRMED,
	   ORDER_PREPARING,
	   ORDER_READY,
	   ORDER_COMPLETED,
	   ORDER_CANCELLED,
	   PAYMENT_SUCCESS,
	   PAYMENT_FAILED,
       PAYMENT_CANCELLED,
       PAYMENT_REFUNDED,
       
       EMAIL_VERIFICATION,
       RECOMMENDATION,
       PASSWORD_RESET,
       FEEDBACK_RECEIVED
       

}
